logging:
  level: INFO
  loggers:
    user-service: DEBUG

database:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver

  # the username
  user: user

  # the password
  password: root

  # the JDBC URL
  url: jdbc:mysql://mysql:3306/user
